n_bees: 10
n_type1_bees: 5
n_iterations: 400
batch_size: 128
csv: false
adjustment_degree_weight: 0.0
adjustment_degree_gap: 0.1
adjustment_degree_mode: current
adjustment_degree_objective: raw
adjustment_degree_target: 0.2
ignore_type4_max_route_len: false
use_demand_weighted_route_selection: false

defaults:
  - _self_
  - experiment: standard
