ppo:
  n_iterations: 60
  val_period: 10
  n_epochs: 1
  minibatch_size: 32
  horizon: 200
  epsilon: 0.2
  use_gae: true
  gae_lambda: 1.0

discount_rate: 1.0
diff_reward: true
incumbent_reward: false
return_best_routes: false
zero_trim_reward: true
max_trim_actions_per_route: 1
baseline_lr: 0.0005
entropy_weight: 0.0
batch_size: 512
reward_scale: 1.0
edit_step_penalty: 0
forced_halt_penalty: 0
lr: 0.0016134816080499328
decay: 0.0008404361781997002
optimizer: Adam

eval:
  min_route_len: 2
  max_route_len: 12
  n_routes: 10

dataset:
  type: pickle
  kwargs:
    path: datasets/mixed_50
    space_scale: 0.6
    demand_scale: 0.2

defaults:
  - _self_
  - experiment: standard
  - model: bestsofar_feb2023
